feat: add typescript definitions
parse-community/parse-server-api-mail-adapter pull request #90
Opened 2023-10-10 18:56 UTC by tbjers

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/mtrezza/parse-server-api-mail-adapter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/mtrezza/parse-server-api-mail-adapter/issues?q=is%3Aissue).

### Issue Description

Related issue: #89

### Approach

### TODOs before merging

- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)

2023-10-10 19:05 UTC, mtrezza commented
Never mind https://github.com/parse-community/parse-server-api-mail-adapter/pull/90#issuecomment-1756054270, this repository has the release branch as the working branch, hence the comment.

2023-10-10 21:39 UTC, tbjers commented
I am not sure if there is a need to update the documentation with anything. Thoughts, @mtrezza?

2023-10-10 22:29 UTC, mtrezza commented
Wouldn't the typescript definition files normally be committed with the repository? Or how are generated?

2023-10-10 22:32 UTC, tbjers commented
They are automatically generated by the npm build command, so they would be generated at the same time as the rest of the code in lib.

On Tue, Oct 10, 2023, at 18:30, Manuel wrote:
> 
> 
> Wouldn't the typescript definition files normally be committed with the repository? Or how are generated?
> 
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/parse-community/parse-server-api-mail-adapter/pull/90#issuecomment-1756356197>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAIQW7CXBYE4Z2UXJE4KXOLX6XD6RAVCNFSM6AAAAAA522DXWCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONJWGM2TMMJZG4>.
> You are receiving this because you authored the thread.Message ID: ***@***.***>
>

2023-10-10 23:03 UTC, mtrezza commented
Got it; regarding docs I don't think there's anything that needs to be added. This will be a major release without any breaking changes, correct?

2023-10-10 23:51 UTC, tbjers commented
Correct.

On Tue, Oct 10, 2023, at 19:03, Manuel wrote:
> 
> 
> Got it; regarding docs I don't think there's anything that needs to be added. This will be a minor release without any breaking changes, correct?
> 
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/parse-community/parse-server-api-mail-adapter/pull/90#issuecomment-1756414268>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAIQW7D2GQB5GKEBTXTQV3TX6XH5NAVCNFSM6AAAAAA522DXWCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONJWGQYTIMRWHA>.
> You are receiving this because you authored the thread.Message ID: ***@***.***>
>

2023-10-11 17:22 UTC, mtrezza requested changes

2023-10-11 17:22 UTC, mtrezza commented on tsconfig.json
> +  // Change this to match your project
Could you remove these general comments, unless there is one specific to our implementation

2023-10-11 17:27 UTC, mtrezza commented
@sadortun could you review this PR please?

2023-10-11 23:44 UTC, sadortun approved these changes

2023-10-11 23:46 UTC, sadortun commented
@mtrezza Yes, the file should be added to the repository.

2023-10-12 00:21 UTC, tbjers commented
> @sadortun could you review this PR please? I wonder whether TS files should be committed to the repo as the IDE will need them?

cc: @sadortun The files do not need to be committed to the repository because they will be part of the package tarball as they are generated at the same time as everything else in `lib/`. My reasoning here is that we do not commit the generated code to the repository, either.

2023-10-12 16:59 UTC, sadortun commented
@tbjers @mtrezza Ah, I was referring to `tsconfig.json` in this PR. And you're referring to `.d.ts` 😂

If `.d.ts` are generated by the build step, then you don't need them in the repo.

2023-10-12 17:47 UTC, mtrezza commented
Thanks @sadortun for confirming, and thanks @tbjers for the PR; I'll go ahead and merge.

2023-10-12 17:47 UTC, mtrezza approved these changes

2023-10-12 17:48 UTC, merged

2023-10-12 17:54 UTC, parseplatformorg commented
🎉 This pull request has been released in version [3.1.0](https://github.com/parse-community/parse-server-api-mail-adapter/releases/tag/3.1.0)