feat: Add ZeptoMail support
parse-community/parse-server-api-mail-adapter pull request #98
Opened 2024-10-13 08:24 UTC by ashish-naik

- [x ] I am not disclosing a [vulnerability](https://github.com/mtrezza/parse-server-api-mail-adapter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server-api-mail-adapter/issues/97).

### Issue Description
Closes https://github.com/parse-community/parse-server-api-mail-adapter/issues/97

### Approach
Add payload converter method to convert payload to ZeptoMail format.

### TODOs before merging
- [x ] Add test cases
- [ ] Add entry to changelog
- [x] Add changes to documentation (guides, repository pages, in-code descriptions)

2024-10-13 08:50 UTC, mtrezza commented on src/ApiPayloadConverter.js
> +  static zeptomail(originalPayload) {
Could you add the provider API version (not SDK version) to the name, e.g. `zeptomail_v1`?

2024-10-13 10:53 UTC, ashish-naik commented on src/ApiPayloadConverter.js
> +  static zeptomail(originalPayload) {
do you mean call should like below

 `await zeptoMaiClient.sendMail({api:'1.1',zeptoMailPayload});`

2024-10-13 19:05 UTC, ashish-naik commented on src/ApiPayloadConverter.js
> +  static zeptomail(originalPayload) {
Please check now. Hope i understood your ask correctly.

2024-10-14 17:02 UTC, ashish-naik commented on README.md
> +                const zeptoMailPayload = ApiPayloadConverter.zeptomail({api: '1.1', originalPayload: payload});
I did not find any documentation about this so will need bit of help. 

Does this look like correct way to check?

`semver.satisfies(version, "1.1.0", { includePrerelease: true })`

2024-10-14 20:27 UTC, mtrezza commented on README.md
> +                const zeptoMailPayload = ApiPayloadConverter.zeptomail({api: '1.1', originalPayload: payload});
After some thought I believe it may be enough to just take the api version `1.1` as a string and do a select/case:

```
select(api) {
  case '1.1': {
    ...
  }
  default: {
    // Throw error unsupported API version
  }
}
```

2024-10-15 17:24 UTC, ashish-naik commented on README.md
> +                const zeptoMailPayload = ApiPayloadConverter.zeptomail({api: '1.1', originalPayload: payload});
Done

2024-10-16 00:06 UTC, mtrezza requested changes
The linter settings seem to be quite weak, I found a few code style issues (spaces, missing brackets, semicolons, etc). I may have missed some, could you look through all the changes again to make sure the style is consistent?

2024-10-16 00:06 UTC, mtrezza commented on spec/ApiMailAdapter.spec.js
> +        const multipleRecepientExamplePayload = {
use same syntax as in existing tests for clarity:

```suggestion
        const examplePayload = {
```

2024-10-16 00:06 UTC, mtrezza commented on spec/ApiMailAdapter.spec.js
> +        });
this doesn't look right, you are comparing payload against itself

2024-10-16 00:06 UTC, mtrezza commented on spec/ApiMailAdapter.spec.js
> +        expect(replyToAddresses).toContain(secondAddress);
this doesn't look right, you are comparing payload against itself

2024-10-16 00:06 UTC, mtrezza commented on README.md
> +                const zeptoMailPayload = ApiPayloadConverter.zeptomail({api: '1.1', originalPayload: payload});
```suggestion
                const zeptoMailPayload = ApiPayloadConverter.zeptomail({ api: '1.1', originalPayload: payload });
```

2024-10-16 18:12 UTC, ashish-naik commented on src/ApiPayloadConverter.js
> +          }
Editor showed error when adding semicolon at this place so didn't.

2024-10-16 18:17 UTC, ashish-naik commented on src/ApiPayloadConverter.js
> +              }
This gives error so didn't.

2024-10-16 18:26 UTC, ashish-naik commented
Thanks for your patience. I have tried to fix the issues. Lot of new things for me.

2024-10-16 18:33 UTC, mtrezza commented on src/ApiPayloadConverter.js
> +   * @param {Object} originalPayload The original payload (provider agnostic). originalPayload has two components 1. api and 2. payload.
JSDoc notation for this is:

```suggestion
   * @param {Object} originalPayload The original payload
   * @param {String} originalPayload.api The provider API version.
   * @param {String} originalPayload.payload The payload to convert to be compatible with the provider API.
```

2024-10-16 18:34 UTC, mtrezza commented on src/ApiPayloadConverter.js
> +   * @param {String} originalPayload.payload The payload to convert to be compatible with the provider API.
```suggestion
   * Converts the mail payload for the ZeptoMail.
   * @param {Object} originalPayload The original payload
   * @param {String} originalPayload.api The provider API version.
   * @param {Object} originalPayload.payload The payload to convert to be compatible with the provider API.
```

2024-10-17 21:24 UTC, mtrezza commented on README.md
> +let zeptoMaiClient = new SendMailClient({url, token});
```suggestion
const zeptoMaiClient = new SendMailClient({ url, token });
```

2024-10-17 21:24 UTC, mtrezza commented on README.md
> +                const zeptoMailPayload = ApiPayloadConverter.zeptomail({ api: '1.1', originalPayload: payload});
```suggestion
                const zeptoMailPayload = ApiPayloadConverter.zeptomail({ api: '1.1', payload });
```

I believe `payload` is the correct key.

2024-10-17 21:24 UTC, mtrezza commented on src/ApiPayloadConverter.js
> +  static zeptomail(originalPayload) {
```suggestion
  static zeptomail(data) {
```

Just to avoid confusion, I would call the container object `data` or something else instead of `originalPayload`, since it already has a child `payload`.

2024-10-18 20:27 UTC, mtrezza commented
Thanks, let's see the CI...

2024-10-18 23:02 UTC, mtrezza commented
Fixed codecov in https://github.com/parse-community/parse-server-api-mail-adapter/pull/99 to make the CI pass.

2024-10-18 23:03 UTC, mtrezza commented on README.md
> +
```suggestion
```

2024-10-18 23:03 UTC, mtrezza commented on spec/ApiMailAdapter.spec.js
> +
```suggestion
```

2024-10-18 23:03 UTC, mtrezza commented on spec/ApiMailAdapter.spec.js
> +      it('converts single recepient payload for ZeptoMail', () => {
```suggestion
      it('converts single recepient payload', () => {
```

2024-10-18 23:04 UTC, mtrezza commented on spec/ApiMailAdapter.spec.js
> +      it('converts multiple recepients payload for ZeptoMail', () => {
```suggestion
      it('converts multiple recipients payload', () => {
```

2024-10-18 23:10 UTC, mtrezza commented on src/ApiPayloadConverter.js
> +        throw new Error(`Unsupported ZeptoMail API version '${ data.api }'.`);
Could you please add a test for the error? Then we should be good to go.

2024-10-19 07:18 UTC, ashish-naik commented on src/ApiPayloadConverter.js
> +        throw new Error(`Unsupported ZeptoMail API version '${ data.api }'.`);
I woke up thinking about it :) 

Does the test look correct?

2024-10-19 13:19 UTC, mtrezza commented on spec/ApiMailAdapter.spec.js
> +        expect(() => converter.zeptomail({ api: '1.1', payload: examplePayload})).not.toThrow();
```suggestion
        expect(() => converter.zeptomail({ api: 'invalidVersion', payload: examplePayload})).toThrowError(/invalidVersion/);
```

2024-10-19 13:26 UTC, mtrezza approved these changes

2024-10-19 13:26 UTC, merged

2024-10-19 13:27 UTC, ashish-naik commented
Thanks @mtrezza for helping me. This is my first contribution.

2024-10-19 13:28 UTC, mtrezza commented
I will fix the release workflow in the next days, so that this feature can be released on npm.

2024-10-20 00:59 UTC, parseplatformorg commented
🎉 This change has been released in version [4.1.0](https://github.com/parse-community/parse-server-api-mail-adapter/releases/tag/4.1.0)